Test fixed routing comparator
blindpirate/forest-petclinic pull request #4
Opened 2020-08-31 09:42 UTC by shiliyu

2020-08-31 10:01 UTC, blindpirate requested changes

2020-08-31 10:01 UTC, blindpirate commented on core/src/test/java/io/forestframework/core/http/routing/AbstractHandlerIntegrationTest.java
> +public class AbstractHandlerIntegrationTest {
Can you make `PreHandlerIntegrationTest` extends it and remove the duplicate code?

2020-08-31 10:01 UTC, blindpirate commented on core/src/test/java/io/forestframework/core/http/routing/AbstractHandlerIntegrationTest.java
> +    }
```
@AfterEach 
void cleanUp() {
    client.close();
}
```

2020-08-31 10:01 UTC, blindpirate commented on core/src/test/java/io/forestframework/core/http/routing/AbstractHandlerIntegrationTest.java
> +        }
This is test, you can throw everything out and don't catch anything. Not a big issue, though.

2020-08-31 10:01 UTC, blindpirate commented on core/src/test/java/io/forestframework/core/http/routing/AbstractHandlerIntegrationTest.java
> +    }
I would prefer:

```
class HttpResponse {
   int statusCode;
   String body;
   void assert200() {
   }
   void assert404() {
   }
   // Or even 
   // void assertStatusCode(int expectedStatusCode) {}
}

...

public HttpResponse sendRequest(String url) {
        CloseableHttpResponse response = excutable.get();
        return new HttpResponse(statusCode, EntityUtils.toString(response.getEntity());
    }
```

2020-08-31 10:02 UTC, shiliyu commented on core/src/test/java/io/forestframework/core/http/routing/AbstractHandlerIntegrationTest.java
> +public class AbstractHandlerIntegrationTest {
Definitely!

2020-08-31 10:04 UTC, shiliyu commented on core/src/test/java/io/forestframework/core/http/routing/AbstractHandlerIntegrationTest.java
> +        }
alright.

2020-08-31 10:06 UTC, shiliyu commented on core/src/test/java/io/forestframework/core/http/routing/AbstractHandlerIntegrationTest.java
> +    }
yes, this makes more sense.

2020-08-31 10:06 UTC, shiliyu commented on core/src/test/java/io/forestframework/core/http/routing/AbstractHandlerIntegrationTest.java
> +    }
will fix it.

2020-09-01 02:27 UTC, blindpirate approved these changes

2020-09-01 02:27 UTC, merged